In [1]:
from de_classes.neo4j_handler import Neo4jUtils
from de_classes.spark_factory import SparkFactory
from de_classes.data_processor import *
from pyspark.sql.types import *

In [2]:
URI = "neo4j+s://0cf2316b.databases.neo4j.io"
neo4j_user = "neo4j"
neo4j_password = "PYIUheqgDra8xkF56RARlNovau4Af05TWzJiMwxu0tI"

In [3]:
driver = Neo4jUtils(URI, neo4j_user, neo4j_password)

In [4]:
spark = SparkFactory("AirQuality-neo4j").get()

25/08/28 18:24:27 WARN Utils: Your hostname, LAPTOP-5G2QRQLJ.localdomain resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
25/08/28 18:24:27 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/08/28 18:24:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
25/08/28 18:24:32 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
25/08/28 18:24:32 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
25/08/28 18:24:32 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.

In [6]:
schema = StructType([
    StructField("Item_Code", IntegerType(),True),
    StructField("Station_Code",  IntegerType(),True),
    StructField("Measurement_Date",  TimestampType(),True),
    StructField("Average_Value",  DoubleType(),True),
    StructField("Instrument_Status",  IntegerType(),True),
    StructField("Station_Name",  StringType(),True),
    StructField("Latitude",  DoubleType(),True),
    StructField("Longitude",  DoubleType(),True),
    StructField("Address",  StringType(),True),
    StructField("Item_Name",  StringType(),True),
    StructField("Unit",  StringType(),True),
    StructField("Status",  StringType(),True),
])

df = DataLoading.read_csv(spark, "hdfs://localhost:9000/user/student/processed_data", schema)

In [7]:
driver.create_constraints()

Executed:
Executed:
Executed:
Executed:
Executed:

In [8]:
records = [row.asDict() for row in df.collect()]

In [9]:
driver.data_ingestion(records)

In [10]:
hotSpot = driver.hot_spot_query()

In [11]:
hotSpot.head(30)

            Station Pollutant  Bad_Readings  Avg_Value  Worst_Value
0       Gwangjin-gu     PM2.5            75      79.32        138.0
1        Yongsan-gu     PM2.5            75      75.75        137.0
2           Mapo-gu     PM2.5            74      73.04        128.0
3       Jungnang-gu     PM2.5            72      77.68        146.0
4         Jongno-gu     PM2.5            72      71.39        121.0
5        Gangbuk-gu     PM2.5            71      73.52        120.0
6          Nowon-gu     PM2.5            71      73.13        112.0
7       Gangdong-gu     PM2.5            71      69.46        133.0
8        Dongjak-gu     PM2.5            70      66.20        237.0
9      Seongdong-gu     PM2.5            70      65.61        126.0
10    Dongdaemun-gu     PM2.5            69      75.33        141.0
11          Jung-gu     PM2.5            69      69.59        115.0
12       Gangnam-gu     PM2.5            69      66.09        121.0
13          Guro-gu     PM2.5            69      64.62        123.0
14        Gwanak-gu     PM2.5            68      60.19        115.0
15     Yangcheon-gu     PM2.5            67      54.55         90.0
16     Geumcheon-gu     PM2.5            67      54.37        109.0
17     Seodaemun-gu     PM2.5            65      56.22        107.0
18        Dobong-gu     PM2.5            64      62.81        110.0
19       Gangseo-gu     PM2.5            64      62.28        119.0
20     Eunpyeong-gu     PM2.5            64      61.58        121.0
21        Seocho-gu     PM2.5            64      58.41        105.0
22        Songpa-gu     PM2.5            63      59.38        106.0
23  Yeongdeungpo-gu     PM2.5            62      62.34        124.0
24      Seongbuk-gu     PM2.5            61      61.26        112.0
25     Seodaemun-gu      PM10            57     116.05        201.0
26    Dongdaemun-gu      PM10            56     116.05        194.0
27      Jungnang-gu      PM10            53     114.92        178.0
28        Seocho-gu      PM10            52     111.19        178.0
29      Gangdong-gu      PM10            50     115.48        192.0

In [12]:
dailyAvg = driver.daily_avg_query()

In [13]:
dailyAvg

            Day     Station Pollutant  Daily_Avg_Value
0    2017-01-01   Dobong-gu        O3             0.00
1    2017-01-01   Dobong-gu       NO2             0.05
2    2017-01-01   Dobong-gu        CO             0.91
3    2017-01-01   Dobong-gu       SO2             0.01
4    2017-01-01   Dobong-gu      PM10            78.30
..          ...         ...       ...              ...
595  2017-01-04  Yongsan-gu       NO2             0.04
596  2017-01-04  Yongsan-gu        CO             0.93
597  2017-01-04  Yongsan-gu       SO2             0.01
598  2017-01-04  Yongsan-gu      PM10            49.42
599  2017-01-04  Yongsan-gu     PM2.5            39.32

[600 rows x 4 columns]

In [14]:
spark.stop()